name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Load Project
        run: pio project config --json-output
        working-directory: ./Super_Cube_ESP
        
      - name: Build PlatformIO Project
        run: pio run -e nodemcuv2
        working-directory: ./Super_Cube_ESP

      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-files
          path: |
            ./Super_Cube_ESP/.pio/build/nodemcuv2/firmware.bin
            ./Super_Cube_ESP/.pio/build/nodemcuv2/firmware.elf
